version: '2'
services:
  newsletter-db:
    image: postgres:10.5
  newsletter-ms:
    image: menoguera/sa_newsletter_mailer_ms
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    ports:
      - "4000:4000"
    depends_on:
      - newsletter-db