version: '2'
services:
  newsletter-db:
    image: postgres:latest
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
  newsletter-ms:
    image: menoguera/sa_newsletter_mailer_ms
    volumes:
      - '.:/app'
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    ports:
      - "4000:4000"
    depends_on:
      - newsletter-db